- name: Patch Process 2
  run: |
    chmod +x script2.sh
    ./script2.sh

    echo "✅ Fichiers disponibles après script2.sh :"
    ls -lh

    if [ ! -f recovery-patched.img ]; then
      echo "❌ recovery-patched.img manquant, annulation"
      exit 1
    fi

    python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
    python3 avbtool add_hash_footer --partition_name recovery \
      --partition_size $(wc -c < recovery.img) \
      --image recovery-patched.img \
      --key phh.pem --algorithm SHA256_RSA4096
    mkdir -p output
    mv recovery-patched.img output/recovery.img
    cd output
    tar cvf fastbootd-recovery.tar recovery.img
    md5sum fastbootd-recovery.tar >> fastbootd-recovery.tar
    mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
